[package]
name = "rustmesh"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
btleplug = "0.11.8"
hex = "0.4.3"
tokio = { version = "1.48.0", features = ["full"] }
uuid = "1.19.0"
